# -----------------------------------------------------------------------------
# Configuration file for http://travis-ci.org/elasticsearch/elasticsearch-rails
# -----------------------------------------------------------------------------

dist: trusty

sudo: required

language: ruby

services:
  - mongodb

branches:
  only:
    - master
    - travis
    - 2.x

matrix:
  include:
    - rvm: 2.2.6
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: 2.3.3
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: 2.3.3
      jdk: oraclejdk8
      env: TEST_SUITE=integration SERVER=start TEST_CLUSTER_LOGS=/tmp/log TEST_CLUSTER_COMMAND=/tmp/elasticsearch-2.4.3/bin/elasticsearch

before_install:
  - gem update --system --no-rdoc --no-ri
  - gem --version
  - gem install bundler -v 1.14.3 --no-rdoc --no-ri
  - bundle version
  - curl -sS https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.3/elasticsearch-2.4.3.tar.gz | tar xz -C /tmp

install:
  - bundle install
  - rake bundle:clean
  - rake bundle:install

script:
  - rake test:$TEST_SUITE

notifications:
  disable: true
